package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class GUILoginOperatorsController {
	@FXML
	private TextField tfIdentificationStart;
	@FXML
	private TextField tfPasswordStart;
	@FXML
	private Button btnGo;
	@FXML
	private Label lMessageErrorPassword;
	@FXML
	private Button btnCreateAccount;
	@FXML
	private Label lMessageErrorIdentification;

	// Event Listener on Button[#btnGo].onAction
	@FXML
	public void goToStart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCreateAccount].onAction
	@FXML
	public void goToCreateAccount(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIRegistrationOperators.fxml"));
			Parent root = loader.load();//cargar la escena
			GUIRegistrationOperatorsController controller = loader.getController();//cargar el controlador que esta asociado a la vista
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			stage.setOnCloseRequest(e->controller.closeWindows());
			//cerramos como tal la vista
			Stage tem = (Stage) this.btnGo.getScene().getWindow();
			tem.close();
		} catch (Exception e) {
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
	}
}
