package business;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class GUIRegistrationController {
	@FXML
	private TextField tfIdentification;
	@FXML
	private TextField tfSurnames;
	@FXML
	private TextField tfName;
	@FXML
	private Label lMessageErrorIdentification;
	@FXML
	private Button btnRegistrer;
	@FXML
	private TextField tfPassword;
	@FXML
	private Label lMessageErrorPassword;
	@FXML
	private Button btnReturn;

	// Event Listener on Button[#btnRegistrer].onAction
	@FXML
	public void registrerUser(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReturn].onAction
	@FXML
	public void returnToLogin(ActionEvent event) {
		closeWindows();
	}
	
	public void closeWindows() {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUILoginOperators.fxml"));
			Parent root = loader.load();
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			stage.setScene(scene);
			stage.show();
			Stage temp = (Stage) btnRegistrer.getScene().getWindow();
			temp.close();
			//cargar style (por el momento no la vamos a agregar, pero esta linea es la misma que en el main)
		} catch (Exception e) {
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
	}
}
